export default [
  {
    id: 1,
    firstName : "Sarrafoğlu Holding A.Ş.",
    lastName : "",
    personalPhone : "05329876543",
    workPhone : "05329876543",
    email:"info@sarrafoglu.com.tr",
    identityNo : "12309876566",
    advancePayment: "50000",
    customerTypeId : 2,
    paymentMethodId: 1,
    customerSourceId: 1,
    isActive : true,
    createdDate : "07/03/2015",
    createdBy : 1,
    updatedDate : null,
    updatedBy : null,
    deletedDate : null,
    deletedBy : null,
    guid : "",

  },
  {
    id: 2,
    firstName : "Deniz",
    lastName : "Tekin",
    personalPhone : "05329876543",
    workPhone : "05329876543",
    email:"deniz.tekin@gmail.com",
    identityNo : "12309876566",
    advancePayment: "25000",
    customerTypeId : 1,
    paymentMethodId: 1,
    customerSourceId: 2,
    isActive : false,
    createdDate : "07/03/2015",
    createdBy : 1,
    updatedDate : null,
    updatedBy : null,
    deletedDate : null,
    deletedBy : null,
    guid : "",
  },
  {
    id: 3,
    firstName : "Selim",
    lastName : "Kara",
    personalPhone : "05329876543",
    workPhone : "05329876543",
    email:"selim.kara@gmail.com",

    identityNo : "12309876566",
    advancePayment: "85000",
    customerTypeId : 1,
    paymentMethodId: 1,
    customerSourceId: 3,
    isActive : false,
    createdDate : "07/03/2015",
    createdBy : 1,
    updatedDate : null,
    updatedBy : null,
    deletedDate : null,
    deletedBy : null,
    guid : "",

  },
  {
    id: 4,
    firstName : "Akgün",
    lastName : "Taşkın",
    personalPhone : "05329876543",
    email:"akgun.taskin@gmail.com",

    workPhone : "05329876543",
    identityNo : "12309876566",
    advancePayment: "60000",
    customerTypeId : 1,
    paymentMethodId: 1,
    customerSourceId: 3,
    isActive : false,
    createdDate : "07/03/2015",
    createdBy : 1,
    updatedDate : null,
    updatedBy : null,
    deletedDate : null,
    deletedBy : null,
    guid : "",

  },
 
];
